#if !defined(AFX_STDAFX_H__931C3690_767C_4238_B25D_05FCCF2961B2__INCLUDED_)
#define AFX_STDAFX_H__931C3690_767C_4238_B25D_05FCCF2961B2__INCLUDED_

// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#define VC_EXTRALEAN		// Exclude rarely-used stuff from Windows headers

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions
#include <afxcmn.h>			// MFC support for Windows 95 Common Controls
#include "debug.h"			// For ASSERT, VERIFY, and TRACE
#include <customaw.h>		// Custom AppWizard interface

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_STDAFX_H__931C3690_767C_4238_B25D_05FCCF2961B2__INCLUDED_)
