CPUA_GHz = 0.5 # 自行修改
CPUB_GHz = 1
V_A = 5
V_B = 4
dynamic_powerconsumption_A = 90
dynamic_powerconsumption_B = 40
static_powerconsumption_A = 10
static_powerconsumption_B = 30
Capacitor_A = 0.5*dynamic_powerconsumption_A/(V_A ** 2*CPUA_GHz*10 ** 9)
Capacitor_A = 0.5*dynamic_powerconsumption_B/(V_B ** 2*CPUB_GHz*10 ** 9)
total_powerconsumption_A = static_powerconsumption_A+dynamic_powerconsumption_A
total_powerconsumption_B = static_powerconsumption_B+dynamic_powerconsumption_B
static_total_ratio_A = static_powerconsumption_A/total_powerconsumption_A
static_dynamic_ratio_A = static_powerconsumption_A/dynamic_powerconsumption_A
static_total_ratio_B = static_powerconsumption_B/total_powerconsumption_B
static_dynamic_ratio_B = static_powerconsumption_B/dynamic_powerconsumption_B
